### ISSUE TITLE
Pakistan/India initial years

### ISSUE THREAD

**Issue by chrisoclary** [svmiller/peacesciencer#12]
Thank you for this package. But I wondered if I could ask about something to make sure I'm not misunderstanding a broader phenomenon. From what I can tell, Pakistan (ccode=770) begins in 1948 according to normal dataset-generating process you outlined on the website but India (ccode==750) begins in 1947. This may be an issue with the underlying COW data but I've not encountered it before when creating other monadic/dyadic datasets in New Gene or EUGene. Many thanks in advance.

**Comment by svmiller** [comment]
According to the Correlates of War and Gleditsch-Ward state system data, India and Pakistan emerge as independent states in 1947. Assuming you loaded `{peacesciencer}` and `{tidyverse}` into your session, you can see this for yourself with the state system data available in the package.

```r
gw_states %>% filter(gwcode %in% c(750, 770))
cow_states %>% filter(ccode %in% c(750, 770))
```
