### ISSUE TITLE
Integrate Gleditsch Expanded Trade and GDP data

### ISSUE THREAD

**Issue by meflynn** [svmiller/peacesciencer#4]
Integrate Gleditsch Expanded Trade and GDP data.

**Comment by svmiller** [comment]
Re: this. I think I want to do one better on the trade data and integrate the Anders et al. surplus GDP. Better coverage + CoW codes. It would really be no issue at all to add Gleditsch's stuff even as my orientation toward state system codes is more CoW than GW.

**Comment by svmiller** [comment]
FWIW, I added the Anders et al. version of the GDP data (along with their SDP measure). I don't know how eager I am to add the Gleditsch data for trade and GDP. The Anders et al. data have the GDP and population estimates that Gleditsch provides, helpfully standardized to *both* CoW and GW systems, which I think supplants what Gleditsch provides to 2011 for just the Gleditsch-Ward states. 

I'll look into the trade data a bit more, even as those data appear to be last updated in 2004. Perhaps the benefit of including the trade data (if not his population/GDP data) is they offer GW coverage where CoW does not. Even then, the data are 20 years out of date.

**Comment by svmiller** [comment]
I'm probably going to close this soon. I already have the GDP data. The trade data were last updated in 2004 and I'm not sure of any recent/planned updates.
