### ISSUE TITLE
ATOP alliances in 2019/20

### ISSUE THREAD

**Issue by joshuaalley** [svmiller/peacesciencer#9]
Thanks for this really useful tool. I'm flagging a small issue with the ATOP alliances data, which has all zeros in dyad-year data for 2019 and 2020. 

Here's a simple example:
`alliance.min <- create_dyadyears(system = "cow",  mry = TRUE,  directed = FALSE) %>%    
    add_atop_alliance()`
Tabulating the number of dyads with a defense pact returns all 0s for defensive alliances in 2019 or 2020. 
`table(alliance.min[alliance.min$year >= 2019, ]$atop_defense)` 

I think these should be NA, as ATOP 5.0 stops at the end of 2018.

**Comment by svmiller** [comment]
Shit. Thank you for bringing that to my attention. I'll fix that now.

**Comment by svmiller** [comment]
Fortunately this was an easy fix, but one necessitated by a lazy (on my end) use of an if-else. https://github.com/svmiller/peacesciencer/commit/535ea4acb75ebdeef4d6d2b373cf76bb5bc9a9ee

**Comment by joshuaalley** [comment]
Glad it was an easy fix!
